# Title of your site
title = "RStudio Education"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://education.rstudio.com/"

# Name the theme folder in `themes/`.
theme = "hugo-tourmaline"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-20375833-3"

relativeurls = false
languageCode = "en-us"
description = "RStudio Education helps people achieve data literacy using the R programming language."
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
# below is critical for non-authors to show up in article listing
preserveTaxonomyNames = true
# uncomment the next line to disable listing authors
# disableKinds = ["taxonomyTerm"]

[permalinks]
  blog = "blog/:year/:month/:slug/"

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackFriday]
    hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	  angledQuotes = false
	  latexDashes = true
    extensions = ["backslashLineBreak"]
  [markup.goldmark.renderer]
    unsafe = true
